#!/bin/bash

set -euo pipefail

hex() {
    openssl rand -hex 8
}

echo "Preparing container..."

COMMAND="shellinaboxd --debug --no-beep --disable-peer-check -u ${SIAB_USER} -g ${SIAB_GROUP} -c /var/lib/shellinabox -p ${SIAB_PORT} --user-css ${SIAB_USERCSS}"

if [ "$SIAB_PKGS" != "openssh shellinabox sudo" ]; then
    sudo pacman -Syu --noconfirm "$SIAB_PKGS"
    sudo pacman -Scc --noconfirm
fi

if [ "$SIAB_SSL" != "true" ]; then
    COMMAND+=" -t"
fi

if [ "${SIAB_ADDUSER}" == "true" ]; then
    if [ "${SIAB_PASSWORD}" == "putsafepasswordhere" ]; then
        SIAB_PASSWORD=$(hex)
        echo "Autogenerated password for user ${SIAB_USER}: ${SIAB_PASSWORD}"
    fi
    echo "${SIAB_USER}:${SIAB_PASSWORD}" | chpasswd
    unset SIAB_PASSWORD
fi

for service in ${SIAB_SERVICE}; do
    COMMAND+=" -s ${service}"
done

if [ "$SIAB_SCRIPT" != "none" ]; then
    if ! curl -s -k "$SIAB_SCRIPT" > /prep.sh; then
        echo "Error downloading script: $SIAB_SCRIPT"
        exit 1
    fi
    chmod +x /prep.sh
    echo "Running $SIAB_SCRIPT..."
    if ! /prep.sh; then
        echo "Error running script: $SIAB_SCRIPT"
        exit 1
    fi
fi

echo "Starting container..."

if [ "$1" = "shellinabox" ]; then
    echo "Executing: $COMMAND"
    exec "$COMMAND"
else
    echo "Executing: $*"
    exec "$@"
fi