#!/bin/bash

# Enable strict mode for better error handling.
set -euo pipefail

# Function to generate a random hexadecimal string.
hex() {
    openssl rand -hex 8
}

echo "Preparing container..."

# Base command for running Shell in a Box.
# Parameters:
# - SIAB_USER: The username for the Shell in a Box user.
# - SIAB_GROUP: The group for the Shell in a Box user.
# - SIAB_PORT: The port number for the Shell in a Box service.
# - SIAB_USERCSS: The CSS file to be used for the Shell in a Box user interface.
# Return:
# - A string representing the base command for running Shell in a Box.
COMMAND="shellinaboxd --debug --no-beep --disable-peer-check -u ${SIAB_USER} -g ${SIAB_GROUP} -c /var/lib/shellinabox -p ${SIAB_PORT} --user-css ${SIAB_USERCSS}"

# Install additional packages if specified.
if [ "$SIAB_PKGS" != "none" ]; then
    sudo yum install -y "$SIAB_PKGS"
    # Installs the packages specified in SIAB_PKGS, using sudo.
    [[ "$SIAB_PKGS2" != "none" ]] && sudo yum install -y "$SIAB_PKGS2"
    # Installs the packages specified in SIAB_PKGS2, using sudo if SIAB_PKGS2 is not none.
    sudo yum clean all
    # Cleans up the yum cache using sudo.
fi

# Disable SSL if SIAB_SSL is not true.
if [ "$SIAB_SSL" != "true" ]; then
    COMMAND+=" -t"
    # Adds the -t flag to the Shell in a Box command to disable SSL.
fi

# Function to create a user if SIAB_ADDUSER is true.
#
# Parameters:
# - SIAB_ADDUSER: A string indicating whether to create a user. If "true", a user will be created.
# - SIAB_USER: The username for the Shell in a Box user.
# - SIAB_PASSWORD: The password for the Shell in a Box user.
#
# Return:
# - None. This function only sets up the user if SIAB_ADDUSER is "true".
if [ "$SIAB_ADDUSER" == "true" ]; then
    # If the default password is used, generate a random password.
    if [ "$SIAB_PASSWORD" == "putsafepasswordhere" ]; then
        SIAB_PASSWORD=$(hex)
        echo "Autogenerated password for user ${SIAB_USER}: ${SIAB_PASSWORD}"
    fi

    # Set the user's password using chpasswd.
    echo "${SIAB_USER}:${SIAB_PASSWORD}" | chpasswd

    # Unset the password variable for security.
    unset SIAB_PASSWORD
fi
