#!/bin/bash

# Enable strict mode for better error handling.
set -euo pipefail

# Function to generate a random hexadecimal string.
hex() {
    openssl rand -hex 8
}

echo "Preparing container..."

# Base command for running Shell in a Box.
COMMAND="shellinaboxd --debug --no-beep --disable-peer-check -u ${SIAB_USER} -g ${SIAB_GROUP} -c /var/lib/shellinabox -p ${SIAB_PORT} --user-css ${SIAB_USERCSS}"
# Constructs the base command to start Shell in a Box with specified user, group, port, and CSS.

# Install additional packages if specified.
if [ "$SIAB_PKGS" != "none" ]; then
    sudo yum install -y "$SIAB_PKGS"
    # Installs the packages specified in SIAB_PKGS, using sudo.
    [[ "$SIAB_PKGS2" != "none" ]] && sudo yum install -y "$SIAB_PKGS2"
    # Installs the packages specified in SIAB_PKGS2, using sudo if SIAB_PKGS2 is not none.
    sudo yum clean all
    # Cleans up the yum cache using sudo.
fi


# Disable SSL if SIAB_SSL is not true.
if [ "$SIAB_SSL" != "true" ]; then
    COMMAND+=" -t"
    # Adds the -t flag to the Shell in a Box command to disable SSL.
fi

# Create a user if SIAB_ADDUSER is true.
if [ "$SIAB_ADDUSER" == "true" ]; then
    # Generate a random password if the default password is used.
    if [ "$SIAB_PASSWORD" == "putsafepasswordhere" ]; then
        SIAB_PASSWORD=$(hex)
        echo "Autogenerated password for user ${SIAB_USER}: ${SIAB_PASSWORD}"
    fi
    # Set the user's password.
    echo "${SIAB_USER}:${SIAB_PASSWORD}" | chpasswd
    # Sets the password for the created user using chpasswd.
    unset SIAB_PASSWORD
    # Unsets the password variable for security.
fi

#!/bin/bash

set -euo pipefail

hex() {
    openssl rand -hex 8
}

echo "Preparing container..."

COMMAND="shellinaboxd --debug --no-beep --disable-peer-check -u ${SIAB_USER} -g ${SIAB_GROUP} -c /var/lib/shellinabox -p ${SIAB_PORT} --user-css ${SIAB_USERCSS}"

if [ "$SIAB_PKGS" != "openssh shellinabox sudo" ]; then
    sudo pacman -Syu --noconfirm "$SIAB_PKGS"
    sudo pacman -Scc --noconfirm
fi

if [ "$SIAB_SSL" != "true" ]; then
    COMMAND+=" -t"
fi

if [ "${SIAB_ADDUSER}" == "true" ]; then
    if [ "${SIAB_PASSWORD}" == "putsafepasswordhere" ]; then
        SIAB_PASSWORD=$(hex)
        echo "Autogenerated password for user ${SIAB_USER}: ${SIAB_PASSWORD}"
    fi
    echo "${SIAB_USER}:${SIAB_PASSWORD}" | chpasswd
    unset SIAB_PASSWORD
fi

for service in ${SIAB_SERVICE}; do
    COMMAND+=" -s ${service}"
done

if [ "$SIAB_SCRIPT" != "none" ]; then
    if ! curl -s -k "$SIAB_SCRIPT" > /prep.sh; then
        echo "Error downloading script: $SIAB_SCRIPT"
        exit 1
    fi
    chmod +x /prep.sh
    echo "Running $SIAB_SCRIPT..."
    if ! /prep.sh; then
        echo "Error running script: $SIAB_SCRIPT"
        exit 1
    fi
fi

echo "Starting container..."

if [ "$1" = "shellinabox" ]; then
    echo "Executing: $COMMAND"
    exec "$COMMAND"
else
    echo "Executing: $*"
    exec "$@"
fi
